# Generated by Django 3.2.6 on 2021-08-22 23:06

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('activities', '0004_alter_activity_title'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Submissions',
            new_name='Submission',
        ),
    ]
