# Generated by Django 3.2.6 on 2021-08-22 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0005_rename_submissions_submission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='grade',
            field=models.IntegerField(),
        ),
    ]
