# Generated by Django 3.2.6 on 2021-08-22 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0007_alter_submission_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='grade',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
